### ISSUE TITLE
css添加-webkit-加不上

### ISSUE THREAD

**Issue by fantasy118** [lqsong/admin-element-vue-docs#3]
字体渐变需要兼容360极速版浏览器，background-clip需要加-webkit-才能生效，但是提交代码时校验工具自动把前缀去掉了，无法保存上

**Comment by lqsong** [comment]
本项目是admin-element-vue的文档

**Comment by fantasy118** [comment]
> 本项目是admin-element-vue的文档

不好意思，最近电脑登不了，用手机没注意看
